spring:
  redis:
    database: 0
    host: 192.168.58.100
    port: 6379
    password:
    jedis:
      pool:
        max-active: 200
        max-idle: 10
        min-idle: 0
        max-wait: -1ms
    timeout: 1000ms
